// Generated by Wrangler on Tue Nov 12 2024 22:32:01 GMT+0000 (Greenwich Mean Time)
// by running `wrangler types`

interface Env {
	hubspotOAuthStore: KVNamespace;
	CLIENT_ID: string;
	CLIENT_SECRET: string;
	PLUGIN_URI: string;
	REDIRECT_URI: string;
	AUTHORIZE_ENDPOINT: string;
	TOKEN_ENDPOINT: string;
	SCOPE: string;
	OPTIONAL_SCOPE: string;
}
